version: '3.8'
services:
  ais:
    container_name: ais
    image: ais
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ENGINE_DB_HOST
      - ENGINE_DB_PASS
      - BLUE_ENGINE_CNAME
      - GREEN_ENGINE_CNAME
    ports:
      - "8080:8080"
