"""Add street code to street_segment

Revision ID: 0d012e999e47
Revises: 9d3e21195d9c
Create Date: 2016-03-15 17:35:56.566388

"""

# revision identifiers, used by Alembic.
revision = '0d012e999e47'
down_revision = '9d3e21195d9c'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('street_segment', sa.Column('street_code', sa.Integer(), nullable=True))
    op.drop_index('idx_street_segment_geom', table_name='street_segment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_street_segment_geom', 'street_segment', ['geom'], unique=False)
    op.drop_column('street_segment', 'street_code')
    ### end Alembic commands ###
