"""empty message

Revision ID: 1adfc3a48581
Revises: a31ad02fb246
Create Date: 2019-01-14 17:15:18.765425

"""

# revision identifiers, used by Alembic.
revision = '1adfc3a48581'
down_revision = 'a31ad02fb246'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_summary', sa.Column('bin_parcel_id', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_summary', 'bin_parcel_id')
    ### end Alembic commands ###
