"""empty message

Revision ID: 4c665272f1fc
Revises: 9bda5e5e605c
Create Date: 2018-04-24 20:52:09.959157

"""

# revision identifiers, used by Alembic.
revision = '4c665272f1fc'
down_revision = '9bda5e5e605c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dor_condominium_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.Text(), nullable=True),
    sa.Column('unit_num', sa.Text(), nullable=True),
    sa.Column('source_object_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dor_condominium_error_parcel_id'), 'dor_condominium_error', ['parcel_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dor_condominium_error_parcel_id'), table_name='dor_condominium_error')
    op.drop_table('dor_condominium_error')
    ### end Alembic commands ###
