"""empty message

Revision ID: 4cb88ab1c025
Revises: 112f42c5fd48
Create Date: 2018-02-23 14:38:24.184815

"""

# revision identifiers, used by Alembic.
revision = '4cb88ab1c025'
down_revision = '112f42c5fd48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dor_parcel_address_analysis', sa.Column('num_parcels_w_address', sa.Integer(), nullable=True))
    op.add_column('dor_parcel_address_analysis', sa.Column('num_parcels_w_mapreg', sa.Integer(), nullable=True))
    op.add_column('dor_parcel_address_analysis', sa.Column('opa_account_nums', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dor_parcel_address_analysis', 'opa_account_nums')
    op.drop_column('dor_parcel_address_analysis', 'num_parcels_w_mapreg')
    op.drop_column('dor_parcel_address_analysis', 'num_parcels_w_address')
    ### end Alembic commands ###
