"""empty message

Revision ID: 5963d86b0ff5
Revises: d06f82a28439
Create Date: 2017-07-11 16:35:12.004782

"""

# revision identifiers, used by Alembic.
revision = '5963d86b0ff5'
down_revision = 'd06f82a28439'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_area_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Text(), nullable=True),
    sa.Column('source_object_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT', srid=2272), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_area_point')
    ### end Alembic commands ###
