"""empty message

Revision ID: 61c98f1023cc
Revises: 4cb88ab1c025
Create Date: 2018-03-22 12:57:34.052836

"""

# revision identifiers, used by Alembic.
revision = '61c98f1023cc'
down_revision = '4cb88ab1c025'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_address_summary_seg_id'), 'address_summary', ['seg_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_summary_seg_id'), table_name='address_summary')
    ### end Alembic commands ###
