"""Make State Plane

Revision ID: 685d969dbc0e
Revises: dd07bbe09379
Create Date: 2016-03-23 11:13:15.912470

"""

# revision identifiers, used by Alembic.
revision = '685d969dbc0e'
down_revision = 'dd07bbe09379'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_pkey', 'address')
    op.alter_column('address', 'street_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('pwd_parcel_street_address_idx', table_name='pwd_parcel')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pwd_parcel_street_address_idx', 'pwd_parcel', ['street_address'], unique=False)
    op.alter_column('address', 'street_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_primary_key('address_pkey', 'address', ['street_address'])
    ### end Alembic commands ###
