"""Add columns linked_address and linked_path to address_tag table.

Revision ID: 7935034cef61
Revises: 2c389a1cea0f
Create Date: 2017-02-03 11:32:56.196296

"""

# revision identifiers, used by Alembic.
revision = '7935034cef61'
down_revision = '2c389a1cea0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_tag', sa.Column('linked_address', sa.Text(), nullable=True))
    op.add_column('address_tag', sa.Column('linked_path', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_tag', 'linked_path')
    op.drop_column('address_tag', 'linked_address')
