"""Add PWD parcels

Revision ID: 9046c00d342e
Revises: 0d012e999e47
Create Date: 2016-03-22 09:28:55.172329

"""

# revision identifiers, used by Alembic.
revision = '9046c00d342e'
down_revision = '0d012e999e47'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwd_parcel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=True),
    sa.Column('address_low', sa.Integer(), nullable=True),
    sa.Column('address_low_suffix', sa.Text(), nullable=True),
    sa.Column('address_low_frac', sa.Text(), nullable=True),
    sa.Column('address_high', sa.Integer(), nullable=True),
    sa.Column('street_predir', sa.Text(), nullable=True),
    sa.Column('street_name', sa.Text(), nullable=True),
    sa.Column('street_suffix', sa.Text(), nullable=True),
    sa.Column('street_postdir', sa.Text(), nullable=True),
    sa.Column('unit_type', sa.Text(), nullable=True),
    sa.Column('unit_num', sa.Text(), nullable=True),
    sa.Column('street_full', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pwd_parcel')
    ### end Alembic commands ###
