"""empty message

Revision ID: 9bda5e5e605c
Revises: c98c0dbcdf02
Create Date: 2018-04-23 16:07:06.803130

"""

# revision identifiers, used by Alembic.
revision = '9bda5e5e605c'
down_revision = 'c98c0dbcdf02'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dor_condominium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.Text(), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=True),
    sa.Column('address_low', sa.Integer(), nullable=True),
    sa.Column('address_low_suffix', sa.Text(), nullable=True),
    sa.Column('address_low_frac', sa.Text(), nullable=True),
    sa.Column('address_high', sa.Integer(), nullable=True),
    sa.Column('street_predir', sa.Text(), nullable=True),
    sa.Column('street_name', sa.Text(), nullable=True),
    sa.Column('street_suffix', sa.Text(), nullable=True),
    sa.Column('street_postdir', sa.Text(), nullable=True),
    sa.Column('unit_num', sa.Text(), nullable=True),
    sa.Column('street_full', sa.Text(), nullable=True),
    sa.Column('source_object_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dor_condominium_parcel_id'), 'dor_condominium', ['parcel_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dor_condominium_parcel_id'), table_name='dor_condominium')
    op.drop_table('dor_condominium')
    ### end Alembic commands ###
