"""Create street tables

Revision ID: 9d3e21195d9c
Revises: None
Create Date: 2016-03-15 10:44:08.174077

"""

# revision identifiers, used by Alembic.
revision = '9d3e21195d9c'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('street_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_predir', sa.Text(), nullable=True),
    sa.Column('street_name', sa.Text(), nullable=True),
    sa.Column('street_suffix', sa.Text(), nullable=True),
    sa.Column('street_postdir', sa.Text(), nullable=True),
    sa.Column('street_full', sa.Text(), nullable=True),
    sa.Column('seg_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('street_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seg_id', sa.Integer(), nullable=True),
    sa.Column('street_predir', sa.Text(), nullable=True),
    sa.Column('street_name', sa.Text(), nullable=True),
    sa.Column('street_suffix', sa.Text(), nullable=True),
    sa.Column('street_postdir', sa.Text(), nullable=True),
    sa.Column('street_full', sa.Text(), nullable=True),
    sa.Column('left_from', sa.Integer(), nullable=True),
    sa.Column('left_to', sa.Integer(), nullable=True),
    sa.Column('right_from', sa.Integer(), nullable=True),
    sa.Column('right_to', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('street_segment')
    op.drop_table('street_alias')
    ### end Alembic commands ###
