"""empty message

Revision ID: a31ad02fb246
Revises: 4c665272f1fc
Create Date: 2018-05-30 14:08:46.399360

"""

# revision identifiers, used by Alembic.
revision = 'a31ad02fb246'
down_revision = '4c665272f1fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dor_parcel_address_analysis', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dor_parcel_address_analysis', 'status')
    ### end Alembic commands ###
