"""Rename geometry to geom

Revision ID: b0a8ba013bf7
Revises: d7fb6e5f0d5c
Create Date: 2016-03-28 12:06:46.886442

"""

# revision identifiers, used by Alembic.
revision = 'b0a8ba013bf7'
down_revision = 'd7fb6e5f0d5c'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curb', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=2272), nullable=True))
    op.drop_column('curb', 'geometry')
    op.add_column('geocode', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=2272), nullable=True))
    op.drop_column('geocode', 'geometry')
    op.add_column('multiple_seg_line', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=2272), nullable=True))
    op.drop_column('multiple_seg_line', 'geometry')
    op.add_column('service_area_diff', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=2272), nullable=True))
    op.drop_column('service_area_diff', 'geometry')
    op.add_column('service_area_polygon', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=2272), nullable=True))
    op.drop_column('service_area_polygon', 'geometry')
    op.drop_index('street_alias_seg_id_idx', table_name='street_alias')
    op.drop_index('test_idx', table_name='street_alias')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('test_idx', 'street_alias', ['seg_id'], unique=False)
    op.create_index('street_alias_seg_id_idx', 'street_alias', ['seg_id'], unique=False)
    op.add_column('service_area_polygon', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=2272), autoincrement=False, nullable=True))
    op.drop_column('service_area_polygon', 'geom')
    op.add_column('service_area_diff', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=2272), autoincrement=False, nullable=True))
    op.drop_column('service_area_diff', 'geom')
    op.add_column('multiple_seg_line', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=2272), autoincrement=False, nullable=True))
    op.drop_column('multiple_seg_line', 'geom')
    op.add_column('geocode', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=2272), autoincrement=False, nullable=True))
    op.drop_column('geocode', 'geom')
    op.add_column('curb', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=2272), autoincrement=False, nullable=True))
    op.drop_column('curb', 'geom')
    ### end Alembic commands ###
