"""empty message

Revision ID: b4389b8cf500
Revises: 33a162d501e2
Create Date: 2018-05-25 11:08:02.075844

"""

# revision identifiers, used by Alembic.
revision = 'b4389b8cf500'
down_revision = '33a162d501e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_summary', sa.Column('ng911_guid', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_summary', 'ng911_guid')
    ### end Alembic commands ###
