"""empty message

Revision ID: ccb95ac2e15a
Revises: d06f82a28439
Create Date: 2017-06-29 11:16:45.421180

"""

# revision identifiers, used by Alembic.
revision = 'ccb95ac2e15a'
down_revision = 'd06f82a28439'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pwd_parcel', sa.Column('building_yn', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pwd_parcel', 'building_yn')
    ### end Alembic commands ###
