"""empty message

Revision ID: d06f82a28439
Revises: 0b26af78abf9
Create Date: 2017-06-13 17:30:40.192156

"""

# revision identifiers, used by Alembic.
revision = 'd06f82a28439'
down_revision = '0b26af78abf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_summary', sa.Column('zoning_document_ids', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_summary', 'zoning_document_ids')
    ### end Alembic commands ###
