"""Add ParcelCurb

Revision ID: d7fb6e5f0d5c
Revises: 1ffd47933a30
Create Date: 2016-03-28 11:09:48.757389

"""

# revision identifiers, used by Alembic.
revision = 'd7fb6e5f0d5c'
down_revision = '1ffd47933a30'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_curb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_source', sa.Text(), nullable=True),
    sa.Column('parcel_row_id', sa.Integer(), nullable=True),
    sa.Column('curb_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_curb_geometry', table_name='curb')
    op.drop_index('idx_dor_parcel_geom', table_name='dor_parcel')
    op.drop_index('idx_dor_parcel_error_polygon_shape', table_name='dor_parcel_error_polygon')
    op.drop_index('idx_geocode_geometry', table_name='geocode')
    op.drop_index('idx_multiple_seg_line_geometry', table_name='multiple_seg_line')
    op.drop_index('idx_service_area_diff_geometry', table_name='service_area_diff')
    op.drop_index('idx_service_area_polygon_geometry', table_name='service_area_polygon')
    op.drop_index('street_alias_seg_id_idx', table_name='street_alias')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('street_alias_seg_id_idx', 'street_alias', ['seg_id'], unique=False)
    op.create_index('idx_service_area_polygon_geometry', 'service_area_polygon', ['geometry'], unique=False)
    op.create_index('idx_service_area_diff_geometry', 'service_area_diff', ['geometry'], unique=False)
    op.create_index('idx_multiple_seg_line_geometry', 'multiple_seg_line', ['geometry'], unique=False)
    op.create_index('idx_geocode_geometry', 'geocode', ['geometry'], unique=False)
    op.create_index('idx_dor_parcel_error_polygon_shape', 'dor_parcel_error_polygon', ['shape'], unique=False)
    op.create_index('idx_dor_parcel_geom', 'dor_parcel', ['geom'], unique=False)
    op.create_index('idx_curb_geometry', 'curb', ['geometry'], unique=False)
    op.drop_table('parcel_curb')
    ### end Alembic commands ###
