"""Add Address

Revision ID: dd07bbe09379
Revises: 9046c00d342e
Create Date: 2016-03-22 12:34:13.508698

"""

# revision identifiers, used by Alembic.
revision = 'dd07bbe09379'
down_revision = '9046c00d342e'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=False),
    sa.Column('address_low', sa.Integer(), nullable=True),
    sa.Column('address_low_suffix', sa.Text(), nullable=True),
    sa.Column('address_low_frac', sa.Text(), nullable=True),
    sa.Column('address_high', sa.Integer(), nullable=True),
    sa.Column('street_predir', sa.Text(), nullable=True),
    sa.Column('street_name', sa.Text(), nullable=True),
    sa.Column('street_suffix', sa.Text(), nullable=True),
    sa.Column('street_postdir', sa.Text(), nullable=True),
    sa.Column('unit_type', sa.Text(), nullable=True),
    sa.Column('unit_num', sa.Text(), nullable=True),
    sa.Column('street_full', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('street_address')
    )
    op.drop_index('idx_pwd_parcel_geom', table_name='pwd_parcel')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_pwd_parcel_geom', 'pwd_parcel', ['geom'], unique=False)
    op.drop_table('address')
    ### end Alembic commands ###
