"""Rebuild migrations

Revision ID: e38650f46415
Revises: None
Create Date: 2016-03-31 16:43:47.045969

"""

# revision identifiers, used by Alembic.
revision = 'e38650f46415'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address_street_address_idx', table_name='address')
    op.drop_index('address_link_address_1_idx', table_name='address_link')
    op.drop_index('address_link_address_2_idx', table_name='address_link')
    op.drop_index('address_parcel_street_address_idx', table_name='address_parcel')
    op.drop_index('address_property_street_address_idx', table_name='address_property')
    op.drop_index('address_street_street_address_idx', table_name='address_street')
    op.drop_index('address_tag_street_address_idx', table_name='address_tag')
    op.drop_index('opa_property_street_address_idx', table_name='opa_property')
    op.drop_index('source_address_street_address_idx', table_name='source_address')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('source_address_street_address_idx', 'source_address', ['street_address'], unique=False)
    op.create_index('opa_property_street_address_idx', 'opa_property', ['street_address'], unique=False)
    op.create_index('address_tag_street_address_idx', 'address_tag', ['street_address'], unique=False)
    op.create_index('address_street_street_address_idx', 'address_street', ['street_address'], unique=False)
    op.create_index('address_property_street_address_idx', 'address_property', ['street_address'], unique=False)
    op.create_index('address_parcel_street_address_idx', 'address_parcel', ['street_address'], unique=False)
    op.create_index('address_link_address_2_idx', 'address_link', ['address_2'], unique=False)
    op.create_index('address_link_address_1_idx', 'address_link', ['address_1'], unique=False)
    op.create_index('address_street_address_idx', 'address', ['street_address'], unique=False)
    ### end Alembic commands ###
