"""empty message

Revision ID: f42a92757cfc
Revises: e270c833a1bc
Create Date: 2017-05-20 11:27:21.326282

"""

# revision identifiers, used by Alembic.
revision = 'f42a92757cfc'
down_revision = 'e270c833a1bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'address_summary', ['street_address'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address_summary', type_='unique')
    ### end Alembic commands ###
