"""empty message

Revision ID: f8ceea8e623a
Revises: f42a92757cfc
Create Date: 2017-05-26 09:07:20.572885

"""

# revision identifiers, used by Alembic.
revision = 'f8ceea8e623a'
down_revision = 'f42a92757cfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_summary', sa.Column('eclipse_object_id', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_summary', 'eclipse_object_id')
    ### end Alembic commands ###
